In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [ ]:
train_df = pd.read_excel('Data_Train.xlsx')
train_df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [ ]:
test_df=pd.read_excel('Test_set.xlsx')
test_df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info
0,Jet Airways,6/06/2019,Delhi,Cochin,DEL → BOM → COK,17:30,04:25 07 Jun,10h 55m,1 stop,No info
1,IndiGo,12/05/2019,Kolkata,Banglore,CCU → MAA → BLR,06:20,10:20,4h,1 stop,No info
2,Jet Airways,21/05/2019,Delhi,Cochin,DEL → BOM → COK,19:15,19:00 22 May,23h 45m,1 stop,In-flight meal not included
3,Multiple carriers,21/05/2019,Delhi,Cochin,DEL → BOM → COK,08:00,21:00,13h,1 stop,No info
4,Air Asia,24/06/2019,Banglore,Delhi,BLR → DEL,23:55,02:45 25 Jun,2h 50m,non-stop,No info

In [ ]:
final_df = train_df.append(test_df)
final_df.head()

<ipython-input-6-890d53ff0289>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = train_df.append(test_df)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897.0
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882.0
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0

In [ ]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13354 entries, 0 to 2670
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Date_of_Journey  13354 non-null  object
 2   Source           13354 non-null  object
 3   Destination      13354 non-null  object
 4   Route            13353 non-null  object
 5   Dep_Time         13354 non-null  object
 6   Arrival_Time     13354 non-null  object
 7   Duration         13354 non-null  object
 8   Total_Stops      13353 non-null  object
 9   Additional_Info  13354 non-null  object
 10  Price            10683 non-null  float64
dtypes: float64(1), object(10)
memory usage: 1.2+ MB

In [ ]:
final_df['Date'] = final_df['Date_of_Journey'].str.split('/').str[0].astype(int)
final_df['Month'] = final_df['Date_of_Journey'].str.split('/').str[1].astype(int)
final_df['Year'] = final_df['Date_of_Journey'].str.split('/').str[2].astype(int)
final_df.drop('Date_of_Journey',axis=1,inplace=True)

In [ ]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13354 entries, 0 to 2670
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Source           13354 non-null  object
 2   Destination      13354 non-null  object
 3   Route            13353 non-null  object
 4   Dep_Time         13354 non-null  object
 5   Arrival_Time     13354 non-null  object
 6   Duration         13354 non-null  object
 7   Total_Stops      13353 non-null  object
 8   Additional_Info  13354 non-null  object
 9   Price            10683 non-null  float64
 10  Date             13354 non-null  int64
 11  Month            13354 non-null  int64
 12  Year             13354 non-null  int64
dtypes: float64(1), int64(3), object(9)
memory usage: 1.4+ MB

In [ ]:
#In arrival time- time and date is specified.
#but we already have date fields extra. so now we focus on time field only
final_df['Arrival_Time']=final_df['Arrival_Time'].str.split(' ').str[0]
final_df['Arrival_hour']=final_df['Arrival_Time'].str.split(':').str[0].astype(int)
final_df['Arrival_min']=final_df['Arrival_Time'].str.split(':').str[1].astype(int)
final_df.drop('Arrival_Time',axis=1,inplace=True)

In [ ]:
final_df['Dep_Time']=final_df['Dep_Time'].str.split(' ').str[0]
final_df['Dep_hour']=final_df['Dep_Time'].str.split(':').str[0].astype(int)
final_df['Dep_min']=final_df['Dep_Time'].str.split(':').str[1].astype(int)
final_df.drop('Dep_Time',axis=1,inplace=True)

In [ ]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13354 entries, 0 to 2670
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Source           13354 non-null  object
 2   Destination      13354 non-null  object
 3   Route            13353 non-null  object
 4   Duration         13354 non-null  object
 5   Total_Stops      13353 non-null  object
 6   Additional_Info  13354 non-null  object
 7   Price            10683 non-null  float64
 8   Date             13354 non-null  int64
 9   Month            13354 non-null  int64
 10  Year             13354 non-null  int64
 11  Arrival_hour     13354 non-null  int64
 12  Arrival_min      13354 non-null  int64
 13  Dep_hour         13354 non-null  int64
 14  Dep_min          13354 non-null  int64
dtypes: float64(1), int64(7), object(7)
memory usage: 1.6+ MB

In [ ]:
final_df['Total_Stops'].unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops'],
      dtype=object)

In [ ]:
final_df['Total_Stops']=final_df['Total_Stops'].map({'non-stop':0,'1 stop':1,'2 stops':2,'3 stops':3,'4 stops':4,'nan':2})

In [ ]:
# we dont need route because we already have no.of stops column
final_df.drop('Route',axis=1,inplace=True)

KeyError: "['Route'] not found in axis"

In [ ]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13351 entries, 0 to 2670
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13351 non-null  object
 1   Source           13351 non-null  object
 2   Destination      13351 non-null  object
 3   Duration         13351 non-null  int64
 4   Total_Stops      0 non-null      float64
 5   Additional_Info  13351 non-null  object
 6   Price            10681 non-null  float64
 7   Date             13351 non-null  int64
 8   Month            13351 non-null  int64
 9   Year             13351 non-null  int64
 10  Arrival_hour     13351 non-null  int64
 11  Arrival_min      13351 non-null  int64
 12  Dep_hour         13351 non-null  int64
 13  Dep_min          13351 non-null  int64
dtypes: float64(2), int64(8), object(4)
memory usage: 1.5+ MB

In [ ]:
final_df['Duration']=final_df['Duration'].str.split(' ').str[0].str.split('h').str[0]

AttributeError: Can only use .str accessor with string values!

In [ ]:
#final_df[final_df['Duration']=='5m']
#we are deleting this 2 rows because data is not present correctly there.
#As it is only 2 records we are not trying to modify it, but deleting it

final_df.drop(6474,axis=0,inplace=True)
final_df.drop(2660,axis=0,inplace=True)

In [ ]:
final_df['Duration']=final_df['Duration'].str.split(' ').str[0].str.split('h').str[0].astype(int)

AttributeError: Can only use .str accessor with string values!

In [ ]:
final_df.head()

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dep_hour,Dep_min
0,IndiGo,Banglore,New Delhi,2,NaN,No info,3897.0,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,7,NaN,No info,7662.0,1,5,2019,13,15,5,50
2,Jet Airways,Delhi,Cochin,19,NaN,No info,13882.0,9,6,2019,4,25,9,25
3,IndiGo,Kolkata,Banglore,5,NaN,No info,6218.0,12,5,2019,23,30,18,5
4,IndiGo,Banglore,New Delhi,4,NaN,No info,13302.0,1,3,2019,21,35,16,50

In [ ]:
final_df['Airline'].unique()

array(['IndiGo', 'Air India', 'Jet Airways', 'SpiceJet',
       'Multiple carriers', 'GoAir', 'Vistara', 'Air Asia',
       'Vistara Premium economy', 'Jet Airways Business',
       'Multiple carriers Premium economy', 'Trujet'], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()
# we can use dummies but best approach is to use laberl encoding or one hot encoding as it is train ans test date

In [ ]:
final_df['Airline']=labelencoder.fit_transform(final_df['Airline'])
final_df['Source']=labelencoder.fit_transform(final_df['Source'])
final_df['Destination']=labelencoder.fit_transform(final_df['Destination'])
final_df['Additional_Info']=labelencoder.fit_transform(final_df['Additional_Info'])

In [ ]:
final_df.shape

(13351, 14)

In [ ]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13351 entries, 0 to 2670
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13351 non-null  int64
 1   Source           13351 non-null  int64
 2   Destination      13351 non-null  int64
 3   Duration         13351 non-null  int64
 4   Total_Stops      0 non-null      float64
 5   Additional_Info  13351 non-null  int64
 6   Price            10681 non-null  float64
 7   Date             13351 non-null  int64
 8   Month            13351 non-null  int64
 9   Year             13351 non-null  int64
 10  Arrival_hour     13351 non-null  int64
 11  Arrival_min      13351 non-null  int64
 12  Dep_hour         13351 non-null  int64
 13  Dep_min          13351 non-null  int64
dtypes: float64(2), int64(12)
memory usage: 1.5 MB